### PR TITLE
Workaround ResultSet memory leak

### LINKED ISSUE #85: Memory Leak Suspect in ForwardOnlyResultSet
Hi, i am so glad to be using this wonderful reactive driver for Oracle!   
Thanks

# Application 

- Java Version: 17.0.2 openjdk
- oracle-r2dbc Version: 1.0.0
- r2dbc-pool Version: 0.9.1 
- ojdbc Version: ojdbc11:21.3.0.0

# Description

I have in production an application which, servers a lot of data, and, have many hits per second.   
Basically, it uses cache-aside technique with redis.   
So, go redis, key not in redis, go to oracle, do some mappings, store it into redis. 

It works like a charm, but, when the application is running on a day without interruption, on our apm, I start to see a memory consumption growth, and the garbage collector can not clean the memory and, the memory average starts to growth, and growth and growth.  

I took a heap dump, and, with eclipse memory analyzer I saw that, the heap has a lot of ForwardOnlyResultSet objects, which, it seems that its not closed after the use. 

Here, we can see that we have a lot of instances of **ForwardOnlyResultSet** 
image

Since, we are using r2dbc-pool, with a pool of 5 connections,     
image

I might be missing something, and forgetting to close the result set. Which, is something that I would to on pure jdbc. But, I havent seen nothing here in the docs about that.

# Example of use

I suspect that I am not closing the result set below, I am just closing(returning the connection back to the pool) after each statement 

```java
    public Mono<CouponDto> fetchCoupon(final long itemId, final long couponId, final long subsidiaryId) {
        return Flux.usingWhen(
                connectionPool.create(),
                connection -> Mono.from(connection.createStatement(QUERY)
                        .bind(0, subsidiaryId)
                        .bind(1, itemId)
                        .bind(2, couponId)
                        .execute()
                ).flatMapMany(it -> it.map(mapper)),
                Connection::close,
                ((connection, throwable) -> connection.close()),
                Connection::close
        ).next();
    }

    private final BiFunction<Row, RowMetadata, CouponDto> mapper = (row, rowMetadata) ->
            new CouponDto(
                    row.get("id", Long.class),
                    row.get("discountPercentage", Double.class),
                    row.get("listPrice", Double.class),
                    row.get("discountType", Integer.class)
            );

```

Again, thanks for your help & time! 
Best Regards, Matheus Rambo

### PR DESCRIPTION
**Pull request by Michael-A-McMahon**
Fixes #85

Changes in this branch work around a memory leak caused by Oracle JDBC bug 34545179.

The workaround is to call getMoreResults(CLOSE_ALL_RESULTS) before closing the JDBC statement. This call has Oracle JDBC remove all elements from the ArrayDeque used internally to store ResultSet objects.

I don't have an automated test for this as it would require a way to WeakReference the ResultSet and verify that it gets garbage collected. Oracle R2DBC does not expose the ResultSet object to user code, so I can't access that with test code.

I've verified this by setting a debug breakpoint that triggers on the condition of Oracle JDBC's ArrayDeque not being empty when the statement is closed. I was able to run the full test suite without triggering this breakpoint, so I am confident that this fix will work.

### CODE REVIEW

**Comment by sgtcortez** [comment]
Hi @Michael-A-McMahon do you have any plan to merge this next week?

**Comment by Michael-A-McMahon** [comment]
Yes. There are a few PRs now that should be reviewed. I'll reach out to people how can review and merge.

**Comment by sgtcortez** [comment]
thank u

**Review by jeandelavarene — APPROVED** [review]

**Comment by htejwani** [comment]
Can you please release the version with this fix on maven central

**Comment by Michael-A-McMahon** [comment]
I suspect a Maven Central release will happen soon, possibly by the end of today. I'll keep you updated.

**Comment by Michael-A-McMahon** [comment]
Fix is available in 1.1.0, which is now available in the Maven Central Repository:
https://repo1.maven.org/maven2/com/oracle/database/r2dbc/oracle-r2dbc/1.1.0/

**Pull request merged**
